# This file is a bash script named alm.
# Support the functionality "alm pop"
# which will remove the latest migration file generated by alembic revision --autogenerate
MIGRATION_PATH="./_alembic/versions"
pop() {
    latest_migration_file=$(ls -t $MIGRATION_PATH/migrations | head -n 1)
    if [ -f "$MIGRATION_PATH/$latest_migration_file" ]; then
        rm -i "$MIGRATION_PATH/$latest_migration_file"
    else
        echo "No migration files found."
    fi
}

if [ "$1" == "pop" ]; then
  pop()
fi

